### ISSUE TITLE
"écrivaine" should not be at the end of the list

### ISSUE THREAD

**Issue by astonedf** [GameLab-UNIL-EPFL/Lausanne-1830#196] opened 2022-06-15 16:00 UTC
It should appear "alphabetically" with the words starting with "e"

**Comment by Dobios** [comment] 2022-06-15 16:04
Not something I can handle without manually sorting the list (which is long to implement and doesn't add much to the experience so VERY LOW PRIORITY imo)

**Comment by Dobios** [comment] 2022-06-15 16:05
Also this is a duplicate of #192

**Closed** 2022-06-15 16:27 UTC
